### Get Issues
GET {{baseUrl}}/api/v1/issues?
    token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImV4cCI6MTcyMDA5NTU0NX0.eyJ1c2VySWQiOiJjM2UxNGEwZi04OTFiLTRmZDItOTUxZC1lODg0NDc0NmQwMWMiLCJsb2dpbiI6InJhY29vbiJ9.NjIxZjVkMjJmZWQ1ODQ2ZWIwNTdlNWVjZWFjYzU0ZmJlMjUwY2NlOWVkOTI0ZWMzNWQ5YmYxZGM2MjQ2MzA5Mw==
Accept: application/json
Content-Type: application/json
